AWSTemplateFormatVersion: "2010-09-09"
Description: "S3 bucket for venue-maps static website with CloudFront distribution"

Parameters:
  MyBucketName:
    Description: Name for the S3 bucket
    Type: String
    Default: venue-maps-site

Resources:
  # Origin Access Identity for CloudFront
  OriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: { "Fn::Sub": "Origin Access Identity for ${MyBucketName}" }

  # S3 Bucket for website
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        { "Fn::Sub": "${MyBucketName}-${AWS::AccountId}-${AWS::Region}" }
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - "*"
            AllowedMethods:
              - GET
              - HEAD
            AllowedOrigins:
              - "*"
            MaxAge: 3000
      VersioningConfiguration:
        Status: Enabled

  # CloudFront Distribution
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases: []
        Comment: { "Fn::Sub": "CloudFront distribution for ${MyBucketName}" }
        DefaultCacheBehavior:
          TargetOriginId: { "Fn::Sub": "${MyBucketName}-origin" }
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods: [GET, HEAD, OPTIONS]
          CachedMethods: [GET, HEAD]
          Compress: true
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          DefaultTTL: 86400
          MaxTTL: 31536000
          MinTTL: 0
        CustomErrorResponses:
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
            ErrorCachingMinTTL: 300
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
            ErrorCachingMinTTL: 300
        DefaultRootObject: index.html
        Enabled: true
        HttpVersion: http2
        IPV6Enabled: true
        Origins:
          - DomainName: { "Fn::GetAtt": ["MyS3Bucket", "RegionalDomainName"] }
            Id: { "Fn::Sub": "${MyBucketName}-origin" }
            S3OriginConfig:
              OriginAccessIdentity:
                {
                  "Fn::Sub": "origin-access-identity/cloudfront/${OriginAccessIdentity}",
                }
        PriceClass: PriceClass_All

Outputs:
  BucketName:
    Description: Name of the S3 bucket
    Value: { "Ref": "MyS3Bucket" }
    Export:
      Name: { "Fn::Sub": "${AWS::StackName}-BucketName" }

  CloudFrontDistributionId:
    Description: CloudFront Distribution ID
    Value: { "Ref": "CloudFrontDistribution" }
    Export:
      Name: { "Fn::Sub": "${AWS::StackName}-DistributionId" }

  CloudFrontDomainName:
    Description: CloudFront Distribution Domain Name
    Value: { "Fn::GetAtt": ["CloudFrontDistribution", "DomainName"] }
    Export:
      Name: { "Fn::Sub": "${AWS::StackName}-DomainName" }

  WebsiteURL:
    Description: Website URL via CloudFront
    Value: { "Fn::Sub": "https://${CloudFrontDistribution.DomainName}" }
    Export:
      Name: { "Fn::Sub": "${AWS::StackName}-WebsiteURL" }

  S3BucketURL:
    Description: S3 bucket URL (for deployment)
    Value: { "Fn::Sub": "s3://${MyS3Bucket}" }
    Export:
      Name: { "Fn::Sub": "${AWS::StackName}-S3BucketURL" }
